### ISSUE TITLE
"Play in MPV" doesn't work with Youtube

### ISSUE THREAD

**Issue by Lastique** [woodruffw/ff2mpv#29]
1. Right-click on a Youtube video link.
2. Select "Play in MPV"
3. Nothing happens.

MPV is installed in a system package, youtube-dl is also available in PATH. Running mpv from the command line with the same link works as expected.

Kubuntu 20.04, Firefox 80.0.1, ff2mpv 3.4.

**Comment by woodruffw** [comment]
Thanks for the report. Can you confirm that you've followed all of the native client installation steps?

**Comment by woodruffw** [comment]
Also: there was a recently native client change (#28), so if you installed the native client from `master` instead of the `v3.4` tag it probably won't work with the currently published version of ff2mpv. I've just published v3.5, so once it's approved that part should fix itself.

**Comment by Lastique** [comment]
> Can you confirm that you've followed all of the native client installation steps?

I just installed the extension from [Firefox Addons](https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/).

**Comment by Lastique** [comment]
Here's an example of a Youtube link I tried: https://www.youtube.com/watch?v=5YuSsYGj5S4

**Comment by Lastique** [comment]
Just installed the ff2mpv 3.5 from Firefox Addons, and it still doesn't work the same way.

**Comment by woodruffw** [comment]
> I just installed the extension from [Firefox Addons](https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/).

That's not enough, unfortunately. As the AMO page and README say, you need to also install a native client so that Firefox can execute MPV. You're on Kubuntu, so here are the relevant steps: https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Linux

**Comment by Lastique** [comment]
Thanks, it works now. The Firefox Addons page doesn't describe this process though, you should probably add the installation guide there.

As an unrelated note, the 3.5 version moved "Play in MPV" into a submenu. Is it possible to move it back to the top level of the context menu? Maybe as an option?

**Comment by woodruffw** [comment]
> As an unrelated note, the 3.5 version moved "Play in MPV" into a submenu. Is it possible to move it back to the top level of the context menu? Maybe as an option?

Possibly, I'll need to look into it. That change happened as part of #28, I think.
